### ISSUE TITLE
Add ability to set defaults in knife.rb

### ISSUE THREAD

**Issue by patcon** [garrettux/knife-vagrant#4]
Seems like a next step?

I'm still mulling over whether I think this plugin is an inversion of logic, but it's rally interesting at the very least! Are you using it for anything? Do you do IRC on freenode, by the way?

**Comment by garrettux** [comment]
I agree.  I think I actually started doing that at one point, but that was a while ago.  Any suggestions on the best way to go about it, or is it just a matter of adding this?

```
Chef::Config.from_file('/path/to/knife.rb')
```

Inversion of logic.. lol.  Probably so.  Initially my idea was to use it as a way to run cookbook tests against a Vagrant box locally before uploading to a chef server.  Then test-kitchen came along and it seems like they took care of that for me :)   It was also a way to abstract the Vagrantfile syntax, which was helpful since, at the time, I was working on a team without any prior ruby or Chef experience, and it made it a little easier for them to get started.

I still play around with it occasionally, but I'm moving toward test-kitchen.  I'm usually on #chef and #devopsatl as garrettux.

**Comment by patcon** [comment]
Oh hey, if you're not actively using it yourself, I wouldn't say it's worth implementing the suggestion. I might experiment, but I don't think I'd dig too far into a tool where the maintainer isn't even using it :)

Not sure the best way, but I know `vagrant-dns` adds config options, so that's where I'd look.

And cool, maybe I'll catch you on IRC!

**Comment by garrettux** [comment]
good point :)  Thanks!
